// Código inicial práctica - Tecnologías Emergentes
// Autora: M. García Valls
// Versión: Inicial v0.01

const tripulantes = [
  {
    id: "F20150001",
    nombre: "Carlos",
    apellidos: "Pérez López",
    cargo: "CAPT",
    horasVu: 8500,
    horasSim: 500,
    comDisciplina: false,
  },
  {
    id: "F20160123",
    nombre: "María",
    apellidos: "García Fernández",
    cargo: "FO",
    horasVu: 4000,
    horasSim: 350,
    comDisciplina: false,
  },
  {
    id: "C20180134",
    nombre: "Ana",
    apellidos: "Rodríguez Martínez",
    cargo: "FA",
    horasVu: 1200,
    horasSim: 50,
    comDisciplina: false,
  },
  {
    id: "C20170056",
    nombre: "Pedro",
    apellidos: "Sánchez Domínguez",
    cargo: "FA",
    horasVu: 1500,
    horasSim: 75,
    comDisciplina: true,
  },
  {
    id: "F20140201",
    nombre: "Luis",
    apellidos: "Fernández Ruiz",
    cargo: "CAPT",
    horasVu: 9200,
    horasSim: 600,
    comDisciplina: false,
  },
  {
    id: "C20190112",
    nombre: "Lucía",
    apellidos: "Gómez Ramírez",
    cargo: "FA",
    horasVu: 900,
    horasSim: 20,
    comDisciplina: false,
  },
  {
    id: "F20130145",
    nombre: "Javier",
    apellidos: "Moreno Álvarez",
    cargo: "FO",
    horasVu: 5000,
    horasSim: 450,
    comDisciplina: false,
  },
  {
    id: "F20150067",
    nombre: "Sofía",
    apellidos: "Jiménez Sánchez",
    cargo: "SO",
    horasVu: 3200,
    horasSim: 300,
    comDisciplina: true,
  },
  {
    id: "C20200089",
    nombre: "David",
    apellidos: "López Pérez",
    cargo: "FA",
    horasVu: 1100,
    horasSim: 30,
    comDisciplina: false,
  },
  {
    id: "F20120432",
    nombre: "Marta",
    apellidos: "Torres Gómez",
    cargo: "CAPT",
    horasVu: 9700,
    horasSim: 550,
    comDisciplina: false,
  },
  {
    id: "C20180567",
    nombre: "Raquel",
    apellidos: "Hernández Díaz",
    cargo: "FA",
    horasVu: 1400,
    horasSim: 80,
    comDisciplina: true,
  },
  {
    id: "F20170023",
    nombre: "Alejandro",
    apellidos: "Cruz Moreno",
    cargo: "SO",
    horasVu: 4500,
    horasSim: 400,
    comDisciplina: false,
  },
  {
    id: "F20130199",
    nombre: "Isabel",
    apellidos: "Molina Castro",
    cargo: "FO",
    horasVu: 4700,
    horasSim: 500,
    comDisciplina: true,
  },
  {
    id: "C20150234",
    nombre: "Diego",
    apellidos: "Navarro Torres",
    cargo: "FA",
    horasVu: 1600,
    horasSim: 100,
    comDisciplina: false,
  },
  {
    id: "F20180912",
    nombre: "Beatriz",
    apellidos: "Ortega Sánchez",
    cargo: "FO",
    horasVu: 3500,
    horasSim: 250,
    comDisciplina: false,
  },
  {
    id: "C20210129",
    nombre: "Elena",
    apellidos: "Romero García",
    cargo: "FA",
    horasVu: 800,
    horasSim: 15,
    comDisciplina: false,
  },
  {
    id: "F20190045",
    nombre: "Fernando",
    apellidos: "García Herrera",
    cargo: "SO",
    horasVu: 2800,
    horasSim: 270,
    comDisciplina: true,
  },
  {
    id: "F20160018",
    nombre: "Patricia",
    apellidos: "Martínez López",
    cargo: "CAPT",
    horasVu: 8900,
    horasSim: 500,
    comDisciplina: false,
  },
  {
    id: "C20220345",
    nombre: "Rubén",
    apellidos: "Díaz López",
    cargo: "FA",
    horasVu: 1000,
    horasSim: 25,
    comDisciplina: false,
  },
  {
    id: "F20171004",
    nombre: "Laura",
    apellidos: "Serrano Gil",
    cargo: "FO",
    horasVu: 5100,
    horasSim: 450,
    comDisciplina: true,
  },
];

console.log(tripulantes);
